server:
  port: 8093
  servlet:
    context-path: /inventory
    
spring:
  application:
    name: InventoryService
  datasource:
    url: jdbc:mysql:///ros?createDatabaseIfNotExist=true
    username: root
    password: sudevkk19
    initialization-mode: always
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        namingStrategy: org.hibernate.cfg.PhysicalNamingStrategy
  cloud:
    discovery:
      enabled: false
      
swagger:
  url: https://inventory-service.test.restaurantonesolution.com/inventory

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: https://service-registry.test.restaurantonesolution.com/eureka
  instance:
    hostname: localhost

logging:
  level:
    '[com.ros.inventory]': DEBUG

    # yyoo